// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsIBLSAXTvuXcRzwGfA4XhtB1Vw6_rclE',
    appId: '1:157179099556:web:6fca70eec043ca5d7ee931',
    messagingSenderId: '157179099556',
    projectId: 'livenotes-ca80c',
    authDomain: 'livenotes-ca80c.firebaseapp.com',
    storageBucket: 'livenotes-ca80c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCiF3hJzqj3_QwC5o3bKlB67E502rWFgA',
    appId: '1:157179099556:android:7d261dd56a53010d7ee931',
    messagingSenderId: '157179099556',
    projectId: 'livenotes-ca80c',
    storageBucket: 'livenotes-ca80c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALBaek9AmmLU0uaiqrrxDJnhtQciCPHgk',
    appId: '1:157179099556:ios:613147c941003b677ee931',
    messagingSenderId: '157179099556',
    projectId: 'livenotes-ca80c',
    storageBucket: 'livenotes-ca80c.firebasestorage.app',
    iosBundleId: 'com.example.livenotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALBaek9AmmLU0uaiqrrxDJnhtQciCPHgk',
    appId: '1:157179099556:ios:613147c941003b677ee931',
    messagingSenderId: '157179099556',
    projectId: 'livenotes-ca80c',
    storageBucket: 'livenotes-ca80c.firebasestorage.app',
    iosBundleId: 'com.example.livenotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsIBLSAXTvuXcRzwGfA4XhtB1Vw6_rclE',
    appId: '1:157179099556:web:3baaf715d801732e7ee931',
    messagingSenderId: '157179099556',
    projectId: 'livenotes-ca80c',
    authDomain: 'livenotes-ca80c.firebaseapp.com',
    storageBucket: 'livenotes-ca80c.firebasestorage.app',
  );
}
